sudo: required
dist: trusty
osx_image: xcode8.3
services:
  - docker

deploy:
  provider: bintray
  skip_cleanup: true
  file: "packaging/root/${PACKAGE}-${DIST}-${TARGET}/descriptor.json"
  user: "ntadej"
  key:
    secure: "ODJ5nLdypZBP2EZHbp4d7WrW1jzOxdV4psOOTG2BHUqNEePrY5uurWjqQvTysN0c5UDdqkeIhb7qDxh5leyb0l6cisdv+1DGR8Z+CyDdwhYJXtKTEBeqHY5nbvAuSqsVf7SLekSZC2sauTJOU3a3i8Ig1VhqQacSXBGwTw5cv0c="
  on:
    branch: project/travis

cache:
  ccache: true
  directories:
    - dependencies/vlc
    - $HOME/Qt5.9.1

matrix:
  include:
    - os: linux
      env: DIST=ubuntu TARGET=xenial-amd64 PACKAGE=deb
    - os: linux
      env: DIST=ubuntu TARGET=xenial-i386 PACKAGE=deb
    - os: osx
      env: DIST=macos TARGET=all-x86_64 PACKAGE=apple

branches:
  except:
    - project/appveyor
    - project/docs

language: cpp

before_script: rvm get head > /dev/null 2>&1 || true
install: . packaging/travis/install.sh
script: ./packaging/build PROJECT=vlc-qt CI_COMMIT=${TRAVIS_COMMIT:0:7} CI_TAG=${TRAVIS_TAG} CI_BUILD=${TRAVIS_BUILD_NUMBER} ${DIST}-${TARGET}
after_success: . packaging/travis/after_success.sh
